name: app

type: dotnet:2.0-rc

relationships:
    database: "mysqldb:mysql"

web:
    locations:
        "/":
            allow: true
            scripts: false
            passthru: true
            root: "wwwroot"
    # commands:
    #    start: './WebApplication1'

hooks:
    build: |
        echo "Building application for $DOTNET_DEFAULT_RUNTIME into $PLATFORM_OUTPUT_DIR."
        dotnet publish --runtime "$DOTNET_DEFAULT_RUNTIME" --output "$PLATFORM_OUTPUT_DIR" --self-contained=false

disk: 512

mounts:
    "/wwwroot/etc": "shared:files/wwwroot/etc"
