name: app

type: dnx

relationships:
    database: "mysqldb:mysql"

web:
    locations:
        "/":
            allow: true
            scripts: false
            passthru: true
            root: "wwwroot"
    # commands:
    #    start: './WebApplication1'

hooks:
    build: |
        mkdir src
        mv * src
        cd src
        wget -qO- https://download.microsoft.com/download/E/7/8/E782433E-7737-4E6C-BFBF-290A0A81C3D7/dotnet-dev-debian-x64.1.0.4.tar.gz | tar xz
        ./dotnet restore
        ./dotnet publish -c Release -r debian.8-x64
        cd ..
        mv src/WebApplication1/bin/Release/netcoreapp1.1/debian.8-x64/publish/* .
        mv src/WebApplication1/wwwroot .
        rm -rf src

disk: 256

mounts:
    "/storage": "shared:files/storage"
