name: app

type: dotnet:2.0-rc

relationships:
    database: "mysqldb:mysql"

web:
    locations:
        "/":
            allow: true
            scripts: false
            passthru: true
            root: "wwwroot"
    commands:
        start: 'dotnet ./WebApplication1.dll'

hooks:
    build: |
        dotnet publish --runtime "$DOTNET_DEFAULT_RUNTIME" --output "$PLATFORM_OUTPUT_DIR" --self-contained

disk: 512

mounts:
    "/wwwroot/etc": "shared:files/wwwroot/etc"
