name: app

type: dotnet:2.0-rc

relationships:
    database: "mysqldb:mysql"

web:
    locations:
        "/":
            allow: true
            scripts: false
            passthru: true
            root: "wwwroot"
    # commands:
    #    start: './WebApplication1'

hooks:
    build: |
        DOTNET_CLI_TELEMETRY_OPTOUT=1 dotnet publish --output $PLATFORM_OUTPUT_DIRECTORY --verbose

disk: 256

mounts:
    "/storage": "shared:files/storage"
